### ISSUE TITLE
Select a venue for Jihoo's w3c class

### ISSUE THREAD

**Issue by TheBeege** [LearnToCodeSeoul/organization#2]
We need to figure out a venue for Jihoo's class. Discussion should take place here

**Comment by ghost** [comment]
I think the google campus's cafe is best place. I don't need to use a presentation screen.
I will using Sketch Notes or my laptop's screen.
wow! very quickly start. I saw this link : "https://www.meetup.com/Learn-To-Code-Seoul/events/235670086/ ".
I want to limit people who wants attend it beacuse I have a google campus membership but it apply 4 visitors.

**Comment by TheBeege** [comment]
Okay, we'll do that, then. That's much easier to organize. 

Yeah, that's Alex's event. I thought he was going to focus more on pure JavaScript, but I guess he's doing full web. Can't hurt to have multiple options.

When do you want to hold your event? And when are you available so I can walk you through the Meetup site?

**Comment by ghost** [comment]
Hi. TheBeege. I might start the class on 1st weekend December.
This Saturday, I'm gonna prepare a curriculum of it. Also I will attend to meetup of Bowlling and I want to talk about it with you and other members.

**Comment by ghost** [comment]
ah.. I'm sorry. I'm going to travel at 2th weekend of December, So I can start it from 3th weekend [Saturday]  December.

**Comment by TheBeege** [comment]
@jihooyim Cool, sounds good. Do you want me to post the event for you? Or would you rather I guide how you on how to post it yourself?

**Comment by ghost** [comment]
@TheBeege  I'm sorry for late your reply. I think you post the event after we talk about the class. See you tommorrow. I'm gonna attend Java meetup tommorrow. : )
